


export const GET_CATEGORY_LOAD = "GET_CATEGORY_LOAD"
export const GET_CATEGORY_SUCC = "GET_CATEGORY_SUCC"
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL"

export const GET_ONECATEGORY_LOAD = "GET_ONECATEGORY_LOAD"
export const GET_ONECATEGORY_SUCC = "GET_ONECATEGORY_SUCC"
export const GET_ONECATEGORY_FAIL = "GET_ONECATEGORY_FAIL"


export const ADD_CATEGORY_SUCC = "ADD_CATEGORY_SUCC"
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"

export const DEL_CATEGORY_SUCC = "DEL_CATEGORY_SUCC"
export const DEL_CATEGORY_FAIL = "DEL_CATEGORY_FAIL"

export const EDIT_CATEGORY_SUCC = "EDIT_CATEGORY_SUCC"
export const EDIT_CATEGORY_FAIL = "EDIT_CATEGORY_FAIL"

export const TOOGLE_TRUE = "TOOGLE_TRUE"
export const TOOGLE_FALSE = "TOOGLE_FALSE"







