


export const GET_CATEGORY_LOAD = "GET_CATEGORY_LOAD"
export const GET_CATEGORY_SUCC = "GET_CATEGORY_SUCC"
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL"

export const GET_ONECATEGORY_LOAD = "GET_ONECATEGORY_LOAD"
export const GET_ONECATEGORY_SUCC = "GET_ONECATEGORY_SUCC"
export const GET_ONECATEGORY_FAIL = "GET_ONECATEGORY_FAIL"





