
export const GET_PRODUCTS_SUCC = "GET_PRODUCTS_SUCC"
export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_PRODUCT_SUCC = "GET_PRODUCT_SUCC"
export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const TOOGLE_TRUE = "TOOGLE_TRUE"
export const TOOGLE_FALSE = "TOOGLE_FALSE"

export const ADD_PRODUCT_SUCC = "ADD_PRODUCT_SUCC"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export const EDIT_PRODUCT_SUCC = "EDIT_PRODUCT_SUCC"
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL"


export const DELETE_PRODUCT_SUCC = "DELETE_PRODUCT_SUCC"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"

export const DELETE_PRODUCTBYCATEGORY_SUCC = "DELETE_PRODUCTBYCATEGORY_SUCC"
export const DELETE_PRODUCTBYCATEGORY_FAIL = "DELETE_PRODUCTBYCATEGORY_FAIL"







