
export const GET_PRODUCTS_SUCC = "GET_PRODUCTS_SUCC"
export const GET_PRODUCTS_LOAD = "GET_PRODUCTS_LOAD"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const GET_PRODUCT_SUCC = "GET_PRODUCT_SUCC"
export const GET_PRODUCT_LOAD = "GET_PRODUCT_LOAD"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

